apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/fwfurtado/k8s-stack.git
      revision: HEAD
      directories:
      - path: cluster-addons/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/fwfurtado/k8s-stack.git
        path: './cluster-addons/{{.path.basename}}/'
        targetRevision: HEAD
        helm:
          valueFiles:
          - values.yaml
          ignoreMissingValueFiles: true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true