apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - image: {{ .Values.image.name }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        name: {{ .Values.name }}
        ports:
        - containerPort: {{ .Values.port | default 80 }}
        env:
        - name: PORT
          value: {{ .Values.port | default 80  | quote}}
        {{- if .Values.env }}
        {{- range .Values.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        {{- end }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory | default "64Mi" }}
            cpu: {{ .Values.resources.requests.cpu | default "250m" }}
          limits:
            memory: {{ .Values.resources.limits.memory | default "128Mi" }}
            cpu: {{ .Values.resources.limits.cpu | default "500m" }}
