apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.port | default 80 }}
      targetPort: {{ .Values.targetPort | default .Values.port | default 80 }}
      protocol: TCP
  type: {{ .Values.type | default "ClusterIP" }}
  selector:
    app: {{ .Values.name }}