global:
  image:
    tag: "v2.13.3"

server:
  service:
    type: NodePort # ClusterIP
  extensions:
    enabled: true
    extensionList:
    - name: rollout-extension
      env: 
        - name: EXTENSION_URL
          value:  https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.7/extension.tar
  extraArgs:
  - --insecure

configs:
  cm:
    exec.enabled: true
