apiVersion: v1
kind: ConfigMap
metadata:  
  name: echoserver-load-test-script
  namespace: echoserver
data:
  load-test.js: |-
    import http from 'k6/http';
    import exec from 'k6/execution';
    import { sleep } from 'k6';

    export const options = {
      vus: 10,
      duration: '5s',
    };


    export default function() {
      http.get('http://echoserver-service.echoserver.svc.cluster.local');
      sleep(1);
      console.log('Request sent');
    }

    export function handleSummary(data) {
      console.log('MIMI ENV: ', __ENV.MIMI_ENV);

      const med_latency = data.metrics.iteration_duration.values.med;
      const latency_message = `The median latency was ${med_latency}\n`;

      return {
        stdout: latency_message,
      };
    }