apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: echoserver-load-test
  namespace: echoserver
  annotations:
    mimi: "hello"
spec:
  parallelism: 3
  script:
    configMap:
      name: 'echoserver-load-test-script'
      file: 'load-test.js'
  runner:
    env:
      - name: MIMI_ENV
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
