apiVersion: v1
kind: Service
metadata:
  name: echoserver-service
  namespace: echoserver
spec:
  ports:
    - port: 6188
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app: echoserver