apiVersion: v2
name: postgres
version: 0.1.0
dependencies:
  - name: postgres-operator
    repository: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
    version: "1.14.0"
  - name: postgres-operator-ui
    repository: https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui
    version: "1.14.0"