apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    chart: grafana/grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.16.1
    helm:
      releaseName: grafana
  destination:
    server: "https://kubernetes.default.svc"
    namespace: grafana